env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "in-the-pipeline-yaml"

steps:
  - command: echo $BUILDKITE_ARTIFACT_UPLOAD_DESTINATION
  - command: echo "i am a test"
  - label: ":crab:"
    command: echo "this is a crab"